UPDATE events
SET
    visible = :visible,
    name_no = :name_no,
    name_en = :name_en,
    description_no = :description_no,
    description_en = :description_en,
    informational_no = :informational_no,
    informational_en = :informational_en,
    time_type = :time_type,
    time_start = :time_start,
    time_end = :time_end,
    time_publish = :time_publish,
    time_signup_release = :time_signup_release,
    time_signup_deadline = :time_signup_deadline,
    canceled = :canceled,
    digital = :digital,
    highlight = :highlight,
    image_small = :image_small,
    image_banner = :image_banner,
    link_facebook = :link_facebook,
    link_discord = :link_discord,
    link_signup = :link_signup,
    link_stream = :link_stream,
    capacity = :capacity,
    full_time = :full_time,
    category_id = :category_id,
    organization_id = :organization_id,
    location_id = :location_id,
    parent_id = :parent_id,
    rule_id = :rule_id,
    audience = :audience,
    updated_at = NOW()
WHERE id = :id
RETURNING *;