// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: categories.sql

package db

import (
	"context"
)

const getCategory = `-- name: GetCategory :one
SELECT id, color, name_no, name_en, description_no, description_en, updated_at, created_at FROM "category" WHERE "id" = $1::int LIMIT 1
`

func (q *Queries) GetCategory(ctx context.Context, id int32) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Color,
		&i.NameNo,
		&i.NameEn,
		&i.DescriptionNo,
		&i.DescriptionEn,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
