// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: locations.sql

package db

import (
	"context"
)

const getLocation = `-- name: GetLocation :one
SELECT id, visible, name_no, name_en, type, mazemap_campus_id, mazemap_poi_id, address_street, address_postcode, city_name, coordinate_lat, coordinate_long, url, updated_at, created_at, deleted_at FROM "location" WHERE "id" = $1::int LIMIT 1
`

func (q *Queries) GetLocation(ctx context.Context, id int32) (Location, error) {
	row := q.db.QueryRowContext(ctx, getLocation, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Visible,
		&i.NameNo,
		&i.NameEn,
		&i.Type,
		&i.MazemapCampusID,
		&i.MazemapPoiID,
		&i.AddressStreet,
		&i.AddressPostcode,
		&i.CityName,
		&i.CoordinateLat,
		&i.CoordinateLong,
		&i.Url,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
