// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"
)

type Querier interface {
	// sqlc.embed(event)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	GetAudiencesOfEvent(ctx context.Context, eventID int32) ([]Audience, error)
	GetCategory(ctx context.Context, id int32) (Category, error)
	GetEvent(ctx context.Context, id int32) (Event, error)
	GetEvents(ctx context.Context, arg GetEventsParams) ([]GetEventsRow, error)
	GetLocation(ctx context.Context, id int32) (Location, error)
	GetOrganizationsOfEvent(ctx context.Context, eventID int32) ([]Organization, error)
	GetRule(ctx context.Context, id int32) (Rule, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
}

var _ Querier = (*Queries)(nil)
