// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"
)

type Querier interface {
	// sqlc.embed(event)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateRule(ctx context.Context, arg CreateRuleParams) (Rule, error)
	GetAddressLocations(ctx context.Context, arg GetAddressLocationsParams) ([]GetAddressLocationsRow, error)
	GetAudience(ctx context.Context, id int32) (Audience, error)
	GetAudiences(ctx context.Context) ([]GetAudiencesRow, error)
	GetAudiencesOfEvent(ctx context.Context, eventID int32) ([]Audience, error)
	GetCategories(ctx context.Context) ([]GetCategoriesRow, error)
	GetCategory(ctx context.Context, id int32) (Category, error)
	GetCoordsLocations(ctx context.Context, arg GetCoordsLocationsParams) ([]GetCoordsLocationsRow, error)
	GetEvent(ctx context.Context, id int32) (Event, error)
	GetEvents(ctx context.Context, arg GetEventsParams) ([]GetEventsRow, error)
	GetLocation(ctx context.Context, id int32) (Location, error)
	GetLocations(ctx context.Context, arg GetLocationsParams) ([]Location, error)
	GetMazemapLocations(ctx context.Context, arg GetMazemapLocationsParams) ([]GetMazemapLocationsRow, error)
	GetOrganization(ctx context.Context, shortname string) (Organization, error)
	GetOrganizations(ctx context.Context, arg GetOrganizationsParams) ([]GetOrganizationsRow, error)
	GetOrganizationsOfEvent(ctx context.Context, eventID int32) ([]Organization, error)
	GetRule(ctx context.Context, id int32) (Rule, error)
	GetRules(ctx context.Context, arg GetRulesParams) ([]GetRulesRow, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	UpdateRule(ctx context.Context, arg UpdateRuleParams) (Rule, error)
}

var _ Querier = (*Queries)(nil)
