// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"
)

type Querier interface {
	GetEvents(ctx context.Context) ([]Event, error)
}

var _ Querier = (*Queries)(nil)
